[2024-10-06 05:35:04,261][__main__][INFO] - Current working directory: /workspace/Session-4-pytorch-lightning
[2024-10-06 05:35:04,261][__main__][INFO] - Configuration keys: dict_keys(['data', 'paths'])
[2024-10-06 05:35:04,261][__main__][INFO] - Paths configuration: root_dir: /workspace/Session-4-pytorch-lightning
data_dir: /workspace/Session-4-pytorch-lightning/data
log_dir: /workspace/Session-4-pytorch-lightning/logs
output_dir: /workspace/Session-4-pytorch-lightning/outputs/2024-10-06/05-35-04
work_dir: /workspace/Session-4-pytorch-lightning

[2024-10-06 05:35:04,262][__main__][INFO] - Data configuration: _target_: src.datamodules.dog_breed.DogBreedDataModule
gdrive_url: https://drive.google.com/file/d/15Yk-AaufO41Ocs-mnbgBCW46SsQRFlAI/view?usp=sharing
dl_path: /workspace/Session-4-pytorch-lightning/data/dataset/
train_val_test_split:
- 0.8
- 0.1
- 0.1
batch_size: 32
num_workers: 4
pin_memory: false
seed: 42

[2024-10-06 05:35:04,262][__main__][INFO] - Log directory: /workspace/Session-4-pytorch-lightning/logs
[2024-10-06 05:35:04,267][__main__][INFO] - Train Dataset Size: 773
[2024-10-06 05:35:04,267][__main__][INFO] - Validation Dataset Size: 96
[2024-10-06 05:35:04,267][__main__][INFO] - Test Dataset Size: 98
[2024-10-06 05:35:04,267][__main__][INFO] - Class Names: ['Beagle', 'Boxer', 'Bulldog', 'Dachshund', 'German_Shepherd', 'Golden_Retriever', 'Labrador_Retriever', 'Poodle', 'Rottweiler', 'Yorkshire_Terrier']
[2024-10-06 05:35:04,392][timm.models._builder][INFO] - Loading pretrained weights from Hugging Face hub (timm/resnet18.a1_in1k)
[2024-10-06 05:35:04,523][timm.models._hub][INFO] - [timm/resnet18.a1_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
[2024-10-06 05:35:04,533][timm.models._builder][INFO] - Missing keys (fc.weight, fc.bias) discovered while loading pretrained weights. This is expected if model is being adapted.
[2024-10-06 05:35:10,767][utils.utils][ERROR] - Exception occurred during task execution.
Traceback (most recent call last):
  File "/workspace/Session-4-pytorch-lightning/src/utils/utils.py", line 12, in wrap
    return task_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/src/train.py", line 93, in train
    trainer.fit(model, datamodule=data_module)
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 981, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 1025, in _run_stage
    self.fit_loop.run()
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/fit_loop.py", line 205, in run
    self.advance()
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 140, in run
    self.advance(data_fetcher)
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 250, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 190, in run
    self._optimizer_step(batch_idx, closure)
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 268, in _optimizer_step
    call._call_lightning_module_hook(
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 167, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/core/module.py", line 1306, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/core/optimizer.py", line 153, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/strategies/strategy.py", line 238, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/plugins/precision/precision.py", line 122, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/torch/optim/optimizer.py", line 484, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/torch/optim/optimizer.py", line 89, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/torch/optim/adam.py", line 205, in step
    loss = closure()
           ^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/plugins/precision/precision.py", line 108, in _wrap_closure
    closure_result = closure()
                     ^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 144, in __call__
    self._result = self.closure(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 129, in closure
    step_output = self._step_fn()
                  ^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 317, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 319, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/lightning/pytorch/strategies/strategy.py", line 390, in training_step
    return self.lightning_module.training_step(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/src/models/catdog_classifier.py", line 51, in training_step
    loss, preds, targets = self.model_step(batch)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/src/models/catdog_classifier.py", line 45, in model_step
    logits = self(x)
             ^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/src/models/catdog_classifier.py", line 36, in forward
    return self.model(x)
           ^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/timm/models/resnet.py", line 635, in forward
    x = self.forward_features(x)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/timm/models/resnet.py", line 614, in forward_features
    x = self.conv1(x)
        ^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Session-4-pytorch-lightning/.venv/lib/python3.12/site-packages/torch/utils/data/_utils/signal_handling.py", line 67, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 16644) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.
[2024-10-06 05:35:10,773][utils.utils][INFO] - Task completed. Check the logs folder for details.
